//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Etiketarte.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArteSplit : Common.ModelBase
    {
        public int IdArteSplit { get; set; }
        public int IdArte { get; set; }
        public string Nombre { get; set; }
    
        public virtual Arte Arte { get; set; }
    }
}
