//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Etiketarte.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfEtiketa : Common.ModelBase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ConfEtiketa()
        {
            this.ArteFormas = new HashSet<ArteForma>();
            this.DetalleOfertas = new HashSet<DetalleOferta>();
        }
    
        public int IdConfEtiketa { get; set; }
        public int IdEtiketa { get; set; }
        public string Nombre { get; set; }
        public bool Estado { get; set; }
        public byte[] RowVersion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArteForma> ArteFormas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleOferta> DetalleOfertas { get; set; }
        public virtual Etiketa Etiketa { get; set; }
    }
}
