//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Etiketarte.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleOrden : Common.ModelBase
    {
        public int IdDetalleOrden { get; set; }
        public int IdOrden { get; set; }
        public string CodigoProducto { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> NumeroLineas { get; set; }
        public string Texto { get; set; }
        public int Cantidad { get; set; }
        public decimal Precio { get; set; }
        public string Estado { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual Orden Orden { get; set; }
    }
}
