//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Etiketarte.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleColor : Common.ModelBase
    {
        public int IdDetalleColor { get; set; }
        public int IdColor { get; set; }
        public int IdArteForma { get; set; }
        public bool Estado { get; set; }
    
        public virtual ArteForma ArteForma { get; set; }
        public virtual Color Color { get; set; }
    }
}
