//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Etiketarte.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleOferta : Common.ModelBase
    {
        public int IdDetalleOferta { get; set; }
        public int IdOferta { get; set; }
        public int IdConfEtiketa { get; set; }
        public int IdPresentacion { get; set; }
        public int Cantidad { get; set; }
        public bool Estado { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual ConfEtiketa ConfEtiketa { get; set; }
        public virtual Oferta Oferta { get; set; }
        public virtual Presentacion Presentacion { get; set; }
    }
}
