//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Etiketarte.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orden : Common.ModelBase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orden()
        {
            this.DetalleOrdens = new HashSet<DetalleOrden>();
        }
    
        public int IdOrden { get; set; }
        public int IdUsuario { get; set; }
        public int IdFormaEnvio { get; set; }
        public int IdFormaPago { get; set; }
        public byte[] codigoOrden { get; set; }
        public short codigo_provincia { get; set; }
        public short codigo_canton { get; set; }
        public int codigo_distrito { get; set; }
        public string CodigoPostal { get; set; }
        public string DireccionEnvio { get; set; }
        public string NombreContacto { get; set; }
        public string ApellidoContacto { get; set; }
        public string TelefonoContacto { get; set; }
        public decimal PrecioTotal { get; set; }
        public string TrackingCode { get; set; }
        public byte[] TrackingImage { get; set; }
        public System.DateTime FechaOrden { get; set; }
        public Nullable<System.DateTime> FechaPago { get; set; }
        public Nullable<System.DateTime> FechaEnvio { get; set; }
        public Nullable<System.DateTime> FechaEntrega { get; set; }
        public string Estado { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual CANTON_CR CANTON_CR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleOrden> DetalleOrdens { get; set; }
        public virtual DISTRITO_CR DISTRITO_CR { get; set; }
        public virtual FormaEnvio FormaEnvio { get; set; }
        public virtual FormaPago FormaPago { get; set; }
        public virtual PROVINCIA_CR PROVINCIA_CR { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
